Traceback (most recent call last):
  File "/Users/akirakawai/Library/Python/3.8/lib/python/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Library/Python/3.8/site-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Library/Python/3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Library/Python/3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Library/Python/3.8/site-packages/nbclient/client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "/Library/Python/3.8/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Library/Python/3.8/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# 配列を作る
# np.array(array)
a = np.array([[1, 2, 3], [4, 5, 6]])

# 配列の情報を取得する
print('array: ', a)
print('a.shape: ', a.shape)
print('a.size: ', a.size)
print('a.sum: ', a.sum())
print('a.ndarray', a.ndarray)

# 関数化
def info(array):
    print('array: ', array)
    print('shape: ', array.shape)
    print('size: ', array.size)
    print('sum: ', array.sum())
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
[0;32m<ipython-input-2-325ae2191df3>[0m in [0;36m<module>[0;34m[0m
[1;32m      8[0m [0mprint[0m[0;34m([0m[0;34m'a.size: '[0m[0;34m,[0m [0ma[0m[0;34m.[0m[0msize[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      9[0m [0mprint[0m[0;34m([0m[0;34m'a.sum: '[0m[0;34m,[0m [0ma[0m[0;34m.[0m[0msum[0m[0;34m([0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 10[0;31m [0mprint[0m[0;34m([0m[0;34m'a.ndarray'[0m[0;34m,[0m [0ma[0m[0;34m.[0m[0mndarray[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     11[0m [0;34m[0m[0m
[1;32m     12[0m [0;31m# 関数化[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m

[0;31mAttributeError[0m: 'numpy.ndarray' object has no attribute 'ndarray'
AttributeError: 'numpy.ndarray' object has no attribute 'ndarray'

